CONFIG_PWM=y
CONFIG_GPIO=y
CONFIG_XLED=y

CONFIG_PRINTK=y
CONFIG_SERIAL=y
CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=y

CONFIG_CBPRINTF_NANO=y
CONFIG_CBPRINTF_REDUCED_INTEGRAL=y
CONFIG_TIMEOUT_64BIT=n

CONFIG_MINIMAL_LIBC=y
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=160
CONFIG_MAIN_STACK_SIZE=320
CONFIG_IDLE_STACK_SIZE=64
CONFIG_ISR_STACK_SIZE=128

CONFIG_UART_INTERRUPT_DRIVEN=n
CONFIG_BOOT_BANNER=n
CONFIG_ASSERT=n
CONFIG_ERRNO=n
CONFIG_THREAD_NAME=n
